### ISSUE TITLE
I hope to sponsor more

### ISSUE THREAD

**Issue by meng517** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#90]
Hello, I have contacted you on SKYPE, I hope to sponsor more, please reply, thank you

**Comment by kochlisGit** [comment]
Hello, 
Thank you for your offer about becoming my sponsor. Although I would like to, there are many responsibilities that keep me from improving the version of ProphitBet. Therefore, i let the community test it, find bugs and notify me so i can fix them. Moreoever, I receive suggestions every day of how to improve it, etc. but i cannot even add all of them due to time-restrictions. I really appreciate it however.

**Comment by meng517** [comment]
Hello, I will not prevent you from modifying ProphitBet. I just want to sponsor and will not suggest modifications.

**Comment by meng517** [comment]
If you are free, please check the email
